//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;
use serde::{ Deserialize, Serialize };

#[derive(
  Clone,
  Debug,
  PartialEq,
  DeriveEntityModel,
  Eq,
  Serialize,
  Deserialize
)]
#[sea_orm(table_name = "links")]
pub struct Model {
  pub created_at: DateTimeWithTimeZone,
  pub updated_at: DateTimeWithTimeZone,
  #[sea_orm(primary_key)]
  pub id: i32,
  pub user_id: i32,
  pub url: String,
  pub short_url: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
